export const metadata = {
  title: "Blogs",
  description: "Generated by create next app",
};

export default function ViewDetailLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <>{children}</>;
}
